#!/bin/bash

# Version de l'application
VERSION="20220321"

############################################################################
### DEBUT: NE PAS MODIFIER CETTE SECTION
############################################################################

mount -o remount,exec /tmp
umask 0022

PATH_TO_INSTALL="${1}/textlive/${VERSION}"  # Repertoire d'installation
LOCAL_ARTEFACT="${2}"                       # Depot UdeM des sources externes;
WORKING_BUILD="${3}"                        # Repertoire de compilation
LOG_DIR="${4}/latex-${VERSION}"             # configure make and install logs
GIT_DIR=`dirname $0`                        # Repertoire courant qui contiendra tous les fichiers de git.
MODULEFILES_DIR="${5}"                      # Repertoire de la centralisation des modulefiles

mkdir -p $LOG_DIR
exec &>> "${LOG_DIR}/`date +%Y-%m-%d-%H-%M-%S`-install"

[[ -d ${PATH_TO_INSTALL} ]] && { echo "Repertoire d'installation existant" ; exit 1; }

############################################################################ 
### FIN: NE PAS MODIFIER CETTE SECTION
############################################################################ 

############################################################################ 
### Etape 1:  Telecharger les sources si necessaire dans le depot d'artefact
############################################################################ 

cd $LOCAL_ARTEFACT
[[ ! -e "install-tl-unx-${VERSION}.tar.gz" ]] && {
    echo "# SENS ############ Telechargement des artefacts directements du site officiel";
    wget https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz;
    mv install-tl-unx.tar.gz install-tl-unx-${VERSION}.tar.gz
}

echo "# SENS ############ Decompresser les artefacts"
tar -zxf install-tl-unx-${VERSION}.tar.gz --directory $WORKING_BUILD

# Basculons dans le repertoire de BUILD
cd $WORKING_BUILD/install-tl-${VERSION}

############################################################################ 
### Etape 2: Preparer un fichier de configuration 
############################################################################ 

# Configurer les variables pour une isntallation sans interraction.
cat << EOF >> texlive.profile
selected_scheme scheme-full
TEXDIR ${PATH_TO_INSTALL}
TEXMFCONFIG ~/.texlive/texmf-config
TEXMFHOME ~/texmf
TEXMFLOCAL ${PATH_TO_INSTALL}/texmf-local
TEXMFSYSCONFIG ${PATH_TO_INSTALL}/texmf-config
TEXMFSYSVAR ${PATH_TO_INSTALL}/texmf-var
TEXMFVAR ~/.texlive/texmf-var
binary_x86_64-linux 1
instopt_adjustpath 0
instopt_adjustrepo 0
instopt_letter 0
instopt_portable 0
instopt_write18_restricted 1
tlpdbopt_autobackup 1
tlpdbopt_backupdir tlpkg/backups
tlpdbopt_create_formats 1
tlpdbopt_generate_updmap 0
tlpdbopt_install_docfiles 0
tlpdbopt_install_srcfiles 0
tlpdbopt_post_code 1
tlpdbopt_sys_bin ${PATH_TO_INSTALL}/bin
tlpdbopt_sys_info ${PATH_TO_INSTALL}/share/info
tlpdbopt_sys_man ${PATH_TO_INSTALL}/share/man
EOF


############################################################################ 
### Etape 3: Executer l'installateur avec le fichier de configuration;
############################################################################ 
# Creer le repertoire ou residera l'application
mkdir -p ${PATH_TO_INSTALL}

echo "# SENS ############ Compiler et installer"
./install-tl  --profile texlive.profile --location https://ctan.mirror.globo.tech/systems/texlive/tlnet/

############################################################################ 
### Etape 4: modulefiles
############################################################################ 
sed "s@WHERETO@${PATH_TO_INSTALL}@g" ${GIT_DIR}/modulefiles/latex.lua > $MODULEFILES_DIR/latex-${VERSION}.lua

############################################################################ 
### DEBUT: NE PAS MODIFIER CETTE SECTION
############################################################################ 
# Nettoyer l'environnement de compilation
rm -rf $WORKINGDIR

mount -o remount,noexec /tmp

exit 0;
############################################################################ 
### FIN: NE PAS MODIFIER CETTE SECTION
############################################################################ 