#!/bin/bash

# Version de l'application
VERSION="4.1.3"

############################################################################ 
### DEBUT: NE PAS MODIFIER CETTE SECTION
############################################################################ 

PATH_TO_INSTALL="${1}/R-${VERSION}"     # Repertoire d'installation
LOG_DIR="${2}/R-${VERSION}"             # configure make and install logs
MODULEFILES_DIR="${3}" 

mkdir -p $LOG_DIR
exec &>> "${LOG_DIR}/`date +%Y-%m-%d-%H-%M-%S`-uninstall"

############################################################################ 
### FIN: NE PAS MODIFIER CETTE SECTION
############################################################################ 

[[ -e "${PATH_TO_INSTALL}" ]] && {
    echo "# SENS ############ Supression de l'application ${PATH_TO_INSTALL}";
    time rm -rvf ${PATH_TO_INSTALL};
}

[[ -e "${MODULEFILES_DIR}/R-4.1.3.lua" ]] && {
    echo "# SENS ############ Supression du modulefiles ${MODULEFILES_DIR}/R-4.1.3.lua";
    time rm -v ${MODULEFILES_DIR}/R-4.1.3.lua;
}

exit 0;

############################################################################ 
### DEBUT: NE PAS MODIFIER CETTE SECTION
############################################################################ 

############################################################################ 
### FIN: NE PAS MODIFIER CETTE SECTION
############################################################################ 