#!/bin/bash

# Version de l'application
VERSION="20220321"

############################################################################ 
### DEBUT: NE PAS MODIFIER CETTE SECTION
############################################################################ 

PATH_TO_INSTALL="${1}/textlive/${VERSION}"  # Repertoire d'installation
LOG_DIR="${2}/latex-${VERSION}"             # configure make and install logs
MODULEFILES_DIR="${3}"                      # Repertoire de la centralisation des

mkdir -p $LOG_DIR
exec &>> "${LOG_DIR}/`date +%Y-%m-%d-%H-%M-%S`-uninstall"

############################################################################ 
### FIN: NE PAS MODIFIER CETTE SECTION
############################################################################ 

[[ -e "${PATH_TO_INSTALL}" ]] && {
    echo "# SENS ############ Supression de l'application ${PATH_TO_INSTALL}";
    time rm -rvf ${PATH_TO_INSTALL};
}

[[ -e "${MODULEFILES_DIR}/latex-${20220321}.lua" ]] && {
    echo "# SENS ############ Supression du modulefiles ${MODULEFILES_DIR}/latex-${20220321}.lua";
    time rm -v ${MODULEFILES_DIR}/latex-${20220321}.lua;
}

exit 0;

############################################################################ 
### DEBUT: NE PAS MODIFIER CETTE SECTION
############################################################################ 

############################################################################ 
### FIN: NE PAS MODIFIER CETTE SECTION
############################################################################ 